### ISSUE TITLE
Update stable version in repo from 0.3.1 to 0.3.2

### ISSUE THREAD

**Issue by GermanBluefox** [Newan/ioBroker.webuntis#10]
# Think about update stable version to 0.3.2
**Version**: stable=**0.3.1** (48 days old) => latest=**0.3.2** (30 days old)
**Installs**: stable=**179** (79.91%), latest=**45** (20.09%), total=**224**
Click to [edit](https://github.com/ioBroker/ioBroker.repositories/edit/master/sources-dist-stable.json#L2281)

**Comment by Newan** [comment]
done
