### ISSUE TITLE
"Cannot read Inbox - possible block by scool" should not be an error, but only info

### ISSUE THREAD

**Issue by phoenix-pnp** [Newan/ioBroker.webuntis#11]
**Describe the bug**  
Our school is only providing class accounts without inboxes.
The adapter hourly logs "Cannot read Inbox - possible block by scool".
This should at maximum be a warning or better an info message

**Expected behavior**  
This should at maximum be a warning or idealyan info message

**Screenshots & Logfiles**  
![image](https://user-images.githubusercontent.com/18349726/161933535-8febfb1c-7136-4087-9116-84f60b639d1f.png)

[webuntis.log](https://github.com/Newan/ioBroker.webuntis/files/8425193/webuntis.log)

**Versions:**  
 - Adapter version: 0.3.2
 - JS-Controller version: 4.0.21
 - Node version: v14.19.1
 - Operating system: raspberry os bullseye

**Comment by Newan** [comment]
next release
