### ISSUE TITLE
Update stable version in repo from 0.3.1 to 0.3.3

### ISSUE THREAD

**Issue by GermanBluefox** [Newan/ioBroker.webuntis#12]
# Think about update stable version to 0.3.3
**Version**: stable=**0.3.1** (65 days old) => latest=**0.3.3** (15 days old)
**Installs**: stable=**180** (78.26%), latest=**30** (13.04%), total=**230**
Click to [edit](https://github.com/ioBroker/ioBroker.repositories/edit/master/sources-dist-stable.json#L2281)

**Comment by Newan** [comment]
#1802

**Comment by Newan** [comment]
0.3.4 published
