### ISSUE TITLE
Can't Update to 0.3.4

### ISSUE THREAD

**Issue by Elektrickser** [Newan/ioBroker.webuntis#14]
Hi,

i can't update to 0.3.4.

here my Update-Output:

```
Process exited with code 0
weniger
mehr

$ iobroker upgrade webuntis@0.3.4

Update webuntis from @0.3.1 to @0.3.4

NPM version: 6.14.16

Installing iobroker.webuntis@0.3.4... (System call)

upload [3] webuntis.admin /opt/iobroker/node_modules/iobroker.webuntis/admin/index_m.html index_m.html text/html

upload [2] webuntis.admin /opt/iobroker/node_modules/iobroker.webuntis/admin/style.css style.css text/css

upload [1] webuntis.admin /opt/iobroker/node_modules/iobroker.webuntis/admin/webuntis.png webuntis.png image/png

upload [0] webuntis.admin /opt/iobroker/node_modules/iobroker.webuntis/admin/words.js words.js application/javascript

Process exited with code 0
```

But the Update dosen't work and the version is after the Update 0.3.1

**Comment by muehle79** [comment]
Same here

**Comment by Newan** [comment]
Looks like npm is missing. Check it After holiday

**Comment by Elektrickser** [comment]
It‘s ok no Stress @Newan. The Plugin Works Fine also.

Holen Sie sich Outlook für iOS<https://aka.ms/o0ukef>
________________________________
Von: Newan ***@***.***>
Gesendet: Tuesday, June 21, 2022 7:03:28 PM
An: Newan/ioBroker.webuntis ***@***.***>
Cc: Elektrickser ***@***.***>; Author ***@***.***>
Betreff: Re: [Newan/ioBroker.webuntis] Can't Update to 0.3.4 (Issue #14)


Looks like npm is missing. Check it After holiday

**Comment by Newan** [comment]
npm aktualisiert
