### ISSUE TITLE
crash after configure with login

### ISSUE THREAD

**Issue by Frischubau** [Newan/ioBroker.webuntis#5]
Hi,

I wan't to use this adapter for the school of my son. When I configure the adapter, the adapter crashes with the following log-entries:

webuntis.0 | 2022-02-27 08:52:15.496 | error | DB closed
-- | -- | -- | --
webuntis.0 | 2022-02-27 08:52:15.496 | error | Error: DB closed at Redis.sendCommand (/opt/iobroker/node_modules/ioredis/built/redis/index.js:636:24) at Redis.get (/opt/iobroker/node_modules/ioredis/built/commander.js:122:25) at StateRedisClient.setState (/opt/iobroker/node_modules/@iobroker/db-states-redis/lib/states/statesInRedisClient.js:657:40) at Webuntis.setState (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js:5880:35)
webuntis.0 | 2022-02-27 08:52:15.494 | error | unhandled promise rejection: DB closed
webuntis.0 | 2022-02-27 08:52:15.494 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
webuntis.0 | 2022-02-27 08:52:15.493 | warn | get state error: Connection is closed.
webuntis.0 | 2022-02-27 08:52:15.019 | info | Timetable found on next workind day
webuntis.0 | 2022-02-27 08:52:14.986 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
webuntis.0 | 2022-02-27 08:52:14.985 | info | terminating
webuntis.0 | 2022-02-27 08:52:14.979 | error | Request failed with status code 403

Do you need further information, please contact me.

**Comment by Newan** [comment]
please test 0.3.2 from lastest or github

**Comment by Frischubau** [comment]
Great! Good job! It seems to be working with this version.
