### ISSUE TITLE
Fehler 403

### ISSUE THREAD

**Issue by FirsttheFirst** [Newan/ioBroker.webuntis#6]
Moin,

ich habe versucht mich im Adapter einzuloggen, bekomme aber nur Fehlermeldungen und er macht ständig reconnect.

Vielleicht hilft der Log ja.

Schule: OBS_Walsrode

THX 

Fehler:

<html>
<body>

adapter disabled
--
webuntis.0 | 2022-03-04 18:39:33.781 | error | Request failed with status code 403
webuntis.0 | 2022-03-04 18:39:33.781 | error | Error: Request failed with status code 403 at createError (/opt/iobroker/node_modules/webuntis/node_modules/axios/lib/core/createError.js:16:15) at settle (/opt/iobroker/node_modules/webuntis/node_modules/axios/lib/core/settle.js:17:12) at IncomingMessage.handleStreamEnd (/opt/iobroker/node_modules/webuntis/node_modules/axios/lib/adapters/http.js:312:11) at IncomingMessage.emit (events.js:326:22) at endReadableNT (_stream_readable.js:1241:12) at processTicksAndRejections (internal/process/task_queues.js:84:21)
webuntis.0 | 2022-03-04 18:39:33.781 | error | unhandled promise rejection: Request failed with status code 403
webuntis.0 | 2022-03-04 18:39:33.780 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().

</body>
</html>

**Comment by FirsttheFirst** [comment]
Ich habe eben ein Update auf 0.3.2 gemacht, jetzt connectet er zwar aber ich bekomme keine Daten und er macht dann Meldung das der Adapter ständig abstürzt.

<html>
<body>


webuntis.0 | 2022-03-04 19:24:20.032 | error | Cannot read Inbox - possible block by scool
-- | -- | -- | --
webuntis.0 | 2022-03-04 19:24:19.832 | warn | Clear yet terminated timer 2
webuntis.0 | 2022-03-04 19:24:19.831 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
webuntis.0 | 2022-03-04 19:24:19.830 | info | terminating
webuntis.0 | 2022-03-04 19:24:19.830 | warn | Found uncleared timeouts (report to developer): 2
webuntis.0 | 2022-03-04 19:24:19.826 | error | Server didn't returned any result.
webuntis.0 | 2022-03-04 19:24:19.825 | error | Error: Server didn't returned any result. at WebUntis._request (/opt/iobroker/node_modules/webuntis/index.js:643:42) at processTicksAndRejections (internal/process/task_queues.js:97:5) at async WebUntis.getOwnTimetableForToday (/opt/iobroker/node_modules/webuntis/index.js:300:16)
webuntis.0 | 2022-03-04 19:24:19.825 | error | unhandled promise rejection: Server didn't returned any result.
webuntis.0 | 2022-03-04 19:24:19.824 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
webuntis.0 | 2022-03-04 19:24:19.270 | info | starting. Version 0.3.2 in /opt/iobroker/node_modules/iobroker.webuntis, node: v12.22.5, js-controller: 3.3.22


</body>
</html>

**Comment by Newan** [comment]
Ok das hab ich noch nie gesehen " Server didn't returned any result"

Könntest du mir deine Daten senden? Passwort tauschen, auf info@newan.de
Oder ist das anonym login?

**Comment by Newan** [comment]
Fehler wurde abgefangen in 0.3.3
